import type { AppDefinition, AppId, DesktopIcon, DockItem } from "@/types";

export const APP_DEFINITIONS: Record<AppId, AppDefinition> = {
  finder: {
    id: "finder",
    title: "Finder",
    icon: "finder",
    defaultSize: { width: 820, height: 540 },
    defaultPosition: { x: 160, y: 80 },
    minSize: { width: 520, height: 360 },
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    icon: "terminal",
    defaultSize: { width: 640, height: 400 },
    defaultPosition: { x: 220, y: 140 },
    minSize: { width: 420, height: 280 },
  },
  safari: {
    id: "safari",
    title: "Safari",
    icon: "safari",
    defaultSize: { width: 900, height: 580 },
    defaultPosition: { x: 120, y: 70 },
    minSize: { width: 560, height: 400 },
  },
  photos: {
    id: "photos",
    title: "Photos",
    icon: "photos",
    defaultSize: { width: 760, height: 520 },
    defaultPosition: { x: 180, y: 90 },
  },
  notes: {
    id: "notes",
    title: "Notes",
    icon: "notes",
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 260, y: 120 },
  },
  resume: {
    id: "resume",
    title: "Resume",
    icon: "resume",
    defaultSize: { width: 640, height: 700 },
    defaultPosition: { x: 200, y: 60 },
  },
  projects: {
    id: "projects",
    title: "Projects",
    icon: "projects",
    defaultSize: { width: 780, height: 520 },
    defaultPosition: { x: 150, y: 90 },
  },
  about: {
    id: "about",
    title: "About Me",
    icon: "about",
    defaultSize: { width: 560, height: 420 },
    defaultPosition: { x: 240, y: 110 },
  },
  contact: {
    id: "contact",
    title: "Contact",
    icon: "contact",
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 280, y: 150 },
  },
  music: {
    id: "music",
    title: "Music",
    icon: "music",
    defaultSize: { width: 420, height: 520 },
    defaultPosition: { x: 300, y: 80 },
  },
  settings: {
    id: "settings",
    title: "System Settings",
    icon: "settings",
    defaultSize: { width: 720, height: 500 },
    defaultPosition: { x: 180, y: 100 },
  },
  trash: {
    id: "trash",
    title: "Trash",
    icon: "trash",
    defaultSize: { width: 700, height: 460 },
    defaultPosition: { x: 200, y: 100 },
  },
  sticky: {
    id: "sticky",
    title: "Sticky Notes",
    icon: "sticky",
    defaultSize: { width: 260, height: 280 },
    defaultPosition: { x: 40, y: 60 },
    resizable: false,
  },
};

export const DOCK_ITEMS: DockItem[] = [
  { id: "dock-finder", appId: "finder", title: "Finder", icon: "finder" },
  { id: "dock-launchpad", appId: "projects", title: "Launchpad", icon: "launchpad" },
  { id: "dock-safari", appId: "safari", title: "Safari", icon: "safari" },
  { id: "dock-messages", appId: "contact", title: "Messages", icon: "messages" },
  { id: "dock-mail", appId: "contact", title: "Mail", icon: "mail" },
  { id: "dock-maps", appId: "about", title: "Maps", icon: "maps" },
  { id: "dock-photos", appId: "photos", title: "Photos", icon: "photos" },
  { id: "dock-facetime", appId: "contact", title: "FaceTime", icon: "facetime" },
  { id: "dock-calendar", appId: "about", title: "Calendar", icon: "calendar" },
  { id: "dock-contacts", appId: "contact", title: "Contacts", icon: "contacts" },
  { id: "dock-reminders", appId: "notes", title: "Reminders", icon: "reminders" },
  { id: "dock-notes", appId: "notes", title: "Notes", icon: "notes" },
  { id: "dock-tv", appId: "music", title: "TV", icon: "tv" },
  { id: "dock-music", appId: "music", title: "Music", icon: "music" },
  { id: "dock-podcasts", appId: "music", title: "Podcasts", icon: "podcasts" },
  { id: "dock-appstore", appId: "projects", title: "App Store", icon: "appstore" },
  {
    id: "dock-settings",
    appId: "settings",
    title: "System Settings",
    icon: "settings",
    separatorAfter: true,
  },
  { id: "dock-folder", appId: "projects", title: "Projects", icon: "folder", separatorAfter: true },
  { id: "dock-trash", appId: "trash", title: "Trash", icon: "trash" },
];

export const DEFAULT_DESKTOP_ICONS: DesktopIcon[] = [
  {
    id: "icon-sticky",
    appId: "sticky",
    label: "To do",
    icon: "sticky",
    gridX: 0,
    gridY: 0,
    type: "sticky",
  },
  {
    id: "icon-about",
    appId: "about",
    label: "About Me",
    icon: "about",
    gridX: 0,
    gridY: 3,
    type: "folder",
  },
  {
    id: "icon-resume",
    appId: "resume",
    label: "Resume.pdf",
    icon: "resume",
    gridX: 1,
    gridY: 3,
    type: "file",
  },
  {
    id: "icon-p1",
    appId: "projects",
    label: "Project 01 (BoltBill)",
    icon: "folder",
    gridX: 0,
    gridY: 0,
    align: "right",
    type: "folder",
  },
  {
    id: "icon-p2",
    appId: "projects",
    label: "Project 02 (Quick Neons)",
    icon: "folder",
    gridX: 0,
    gridY: 1,
    align: "right",
    type: "folder",
  },
  {
    id: "icon-p3",
    appId: "projects",
    label: "Project 03 (POS Backend)",
    icon: "folder",
    gridX: 0,
    gridY: 2,
    align: "right",
    type: "folder",
  },
  {
    id: "icon-p4",
    appId: "projects",
    label: "Project 04 (Checkout)",
    icon: "folder",
    gridX: 0,
    gridY: 3,
    align: "right",
    type: "folder",
  },
  {
    id: "icon-trash",
    appId: "trash",
    label: "Don't Look.",
    icon: "trash",
    gridX: 0,
    gridY: 0,
    align: "right",
    type: "trash",
  },
];

export const GRID = {
  cellWidth: 100,
  cellHeight: 104,
  offsetX: 28,
  offsetY: 44,
  iconWidth: 88,
} as const;
